site_name: Chatbot pédagogique pour le Deep Learning
site_description: Cours BTS SIO sur le développement d'un chatbot pédagogique
site_author: Votre Nom
copyright: "© 2025 Atelier-deeplearning"
# site_url: https://ggaillard.github.io/Atelier-deeplearning/  
# repo_url: https://github.com/ggaillard/Atelier-deeplearning  
repo_name: ggaillard/Atelier-deeplearning

theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocs-jupyter
  - mermaid2

nav:
  - Accueil: index.md
  - Carte de progression: carte-progression.md
  - Suivi de progression: suivi-progression.md
  - Module 1 - Fondamentaux:
      - Vue d'ensemble: module1/index.md
      - Introduction pratique: module1/introduction-pratique.md
      - Concepts fondamentaux: module1/concepts-fondamentaux.md
      - Mini-projet individuel: module1/mini-projet.md
      - Auto-évaluation: module1/qcm-evaluation-module1.md
      - Ressources: 
        - Guide Colab: module1/ressources/guide-colab.md     
  - Module 2 - Architectures:
      - Vue d'ensemble: module2/index.md
      - Réseaux convolutifs (CNN): module2/reseaux-convolutifs.md
      - Réseaux récurrents (RNN): module2/reseaux-recurrents.md
      - Auto-évaluation: module2/qcm-evaluation-module2.md
  - Module 3 - Applications:
      - Vue d'ensemble: module3/index.md
      - Frameworks et bonnes pratiques: module3/frameworks.md
      - Intégration de modèles: module3/integration.md
      - Préparation au projet: module3/preparation-projet.md
      - Auto-évaluation: module3/qcm-evaluation-module3.md
  - Module 4 - Projet:
      - Vue d'ensemble: module4/index.md
      - Projet Chatbot: module4/projet-chatbot.md
      - Préparation: module4/preparation-projet.md 
      - Développement: module4/partie1-developpement.md
      - Finalisation: module4/partie2-finalisation.md
      - Présentation: module4/partie3-presentation.md
      - Auto-évaluation: module4/qcm-evaluation-module4.md
  - Glossaire:
      - Glossaire: module1/ressources/glossaire-dl.md           
    - Licences:
      - Licence MIT (Code): https://github.com/ggaillard/Atelier-deeplearning/blob/main/LICENSE
      - Licence CC BY-NC-SA (Contenu): https://github.com/ggaillard/Atelier-deeplearning/blob/main/CONTENT_LICENSE.md
    
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/votre-repo/chatbot-deeplearning
extra_javascript:
  - javascripts/progress.js
extra_css:
  - stylesheets/progress.css