site_name: Chatbot pédagogique pour le Deep Learning
site_description: Cours BTS SIO sur le développement d'un chatbot pédagogique
site_author: Votre Nom
# site_url: https://ggaillard.github.io/Atelier-deeplearning/  
# repo_url: https://github.com/ggaillard/Atelier-deeplearning  
repo_name: ggaillard/Atelier-deeplearning

theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocs-jupyter
  - mermaid2

nav:
  - Accueil: index.md
  - Présentation: presentation.md
  - Carte de progression: carte-progression.md
  - Séance 1:
    - Vue d'ensemble: seance1/index.md
    - Mise en situation: seance1/partie1-mise-en-situation/partie1-mise-en-situation.md
    - Découverte des concepts: seance1/partie2-decouverte-concepts.md
    - Débrief: seance1/partie3-debrief.md
  - Séance 2:
    - Vue d'ensemble: seance2/index.md
    - Mini-projet CNN: seance2/partie1-cnn.md
    - Mini-projet RNN: seance2/partie2-rnn.md
    - Challenge d'amélioration: seance2/partie3-amelioration.md
  - Séance 3:
    - Vue d'ensemble: seance3/index.md
    - Optimisation: seance3/partie1-optimisation.md
    - Frameworks: seance3/partie2-frameworks.md
    - Préparation du projet: seance3/partie3-preparation-projet.md
  - Séance 4:
    - Vue d'ensemble: seance4/index.md
    - Développement: seance4/partie1-developpement.md
    - Finalisation: seance4/partie2-finalisation.md
    - Présentation: seance4/partie3-presentation.md
  - Ressources:
    - Vue d'ensemble: ressources/index.md
    - API Mistral: ressources/api-mistral.md
    - Base de connaissances: ressources/base-connaissances.md
    - Instructions d'intégration: ressources/instructions-integration.md
    - Schémas JSON: ressources/json-schemas.md
  - Évaluation:
    - Vue d'ensemble: evaluation/index.md
    - Répartition des tâches: evaluation/grille-repartition-taches.md
    - Critères d'évaluation: evaluation/criteres-evaluation.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/votre-repo/chatbot-deeplearning
