site_name: Chatbot pédagogique pour le Deep Learning
site_description: Cours BTS SIO sur le développement d'un chatbot pédagogique
site_author: Votre Nom
# site_url: https://ggaillard.github.io/Atelier-deeplearning/  
# repo_url: https://github.com/ggaillard/Atelier-deeplearning  
repo_name: ggaillard/Atelier-deeplearning

theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocs-jupyter
  - mermaid2

nav:
  - Accueil: index.md
  - Carte de progression: carte-progression.md
  - Suivi de progression: suivi-progression.md
  - Module 1 - Fondamentaux:
      - Vue d'ensemble: module1/index.md
      - Introduction pratique: module1/introduction-pratique.md
      - Concepts fondamentaux: module1/concepts-fondamentaux.md
      - Mini-projet individuel: module1/mini-projet.md
      - Ressources: 
        - Notebook Hello World: module1/ressources/hello-world-dl.ipynb
        - Comparaison ML vs DL: module1/ressources/ml-vs-dl-comparison.ipynb
        - Fiche d'observations: module1/ressources/fiche-observations.md
        - Guide Colab: module1/ressources/guide-colab.md
        - Glossaire: module1/ressources/glossaire-dl.md
  - Module 2 - Architectures:
      - Vue d'ensemble: module2/index.md
      - Réseaux convolutifs (CNN): module2/reseaux-convolutifs.md
      - Réseaux récurrents (RNN): module2/reseaux-recurrents.md
      - Ressources:
        - Notebook CNN: module2/ressources/cnn-classification.ipynb
        - Notebook RNN: module2/ressources/rnn-sequence.ipynb
        - Test API Mistral: module2/ressources/api-mistral-test.py
        - Évaluation CNN: module2/ressources/evaluationCNN.md
  - Module 3 - Applications:
      - Vue d'ensemble: module3/index.md
      - Frameworks et bonnes pratiques: module3/frameworks.md
      - Intégration de modèles: module3/integration.md
      - Préparation au projet: module3/preparation-projet.md
      - Ressources:
        - TensorFlow/Keras: module3/ressources/tensorflow-keras-debutants.ipynb
        - Diagnostic de performance: module3/ressources/diagnostic_problemes_performance.md
        - Prototype chatbot: module3/ressources/prototype-chatbot.py
        - Cas d'utilisation: module3/ressources/cas-utilisation-entreprise.md
        - Guide API Mistral: module3/ressources/api-mistral-guide-simple.md
  - Module 4 - Projet:
      - Vue d'ensemble: module4/index.md
      - Développement: module4/developpement.md
      - Finalisation: module4/finalisation.md
      - Présentation: module4/presentation.md
      - Ressources:
        - Template documentation: module4/ressources/modele-documentation-technique.md
        - Exemple base de connaissances: module4/ressources/exemple-base-connaissances.json
        - Grille d'évaluation: module4/ressources/grille-evaluation-projet.md
  - Ressources communes:
      - Vue d'ensemble: ressources/index.md
      - API Mistral: ressources/api-mistral.md
      - Base de connaissances: ressources/base-connaissances.md
      - Schémas JSON: ressources/json-schemas.md
      - Guide étudiant: ressources/guide-etudiant.md
  - Évaluation:
      - Vue d'ensemble: evaluation/index.md
      - Critères d'évaluation: evaluation/criteres-evaluation.md
      - Répartition des tâches: evaluation/grille-repartition-taches.md
      - Checklist d'auto-évaluation: evaluation/checklist-auto-evaluation.md
    
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/votre-repo/chatbot-deeplearning
extra_javascript:
  - javascripts/progress.js
extra_css:
  - stylesheets/progress.css